name: Build app

on:
  push:
  pull_request:
# permissions:
#   contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build app
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0
        with:
          cache: false

      - name: Build app
        run: yarn run build
