name: Build and deploy app

on:
  push:
  pull_request:
# permissions:
#   contents: write

jobs:
  build:
    name: Build and deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0
        with:
          cache: false

      - name: Build app
        run: yarn run build

      # If the app builds successfully, and is not a PR:
      # Deploy to production
      - name: Deploy with ssh
        if: github.event_name != 'pull_request'
        uses: sebastianjnuwu/ssh-action-deploy@v3
        with:
          IP: ${{ secrets.SSH_DEPLOY_IP }}
          USER: ${{ secrets.SSH_DEPLOY_USER }}
          KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          FOLDER: "~/backend-server/dist/"
          RUN: "cd ~/backend-server && git pull && yarn run build && yarn run up"
